<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Targetnet8.0>net8.0</Targetnet8.0>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.Entitynet8.0Core.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Entitynet8.0Core.Tools" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
  </ItemGroup>

</Project>